// frontend/src/lib/components/CredentialForm.svelte
<script lang="ts">
  import { saveCredential, updateCredential, generatePassword, type Credential } from '../api';
  
  export let credential: Credential | null = null;
  export let onClose: () => void;
  export let onSave: () => void;
  
  let title = credential?.title || '';
  let username = credential?.username || '';
  let password = credential?.password || '';
  let url = credential?.url || '';
  let notes = credential?.notes || '';
  let category = credential?.category || 'general';
  let isFavorite = credential?.is_favorite || false;
  let isLoading = false;
  let error = '';
  let showPassword = false;
  
  const isEditing = !!credential;
  
  // 生成密码
  async function handleGeneratePassword() {
    try {
      password = await generatePassword(16, true, true, true, true);
    } catch (e) {
      error = `生成密码失败: ${e}`;
    }
  }
  
  // 保存凭证
  async function handleSubmit() {
    if (!title) {
      error = '请输入标题';
      return;
    }
    if (!password) {
      error = '请输入密码';
      return;
    }
    
    isLoading = true;
    error = '';
    
    const now = new Date().toISOString();
    const credentialData: Credential = {
      id: credential?.id || crypto.randomUUID(),
      title,
      username: username || undefined,
      password,
      url: url || undefined,
      notes: notes || undefined,
      category,
      tags: [],
      created_at: credential?.created_at || now,
      updated_at: now,
      is_favorite: isFavorite,
    };
    
    try {
      const result = isEditing 
        ? await updateCredential(credentialData)
        : await saveCredential(credentialData);
      
      if (result.success) {
        onSave();
        onClose();
      } else {
        error = result.error || '保存失败';
      }
    } catch (e) {
      error = `保存失败: ${e}`;
    } finally {
      isLoading = false;
    }
  }
</script>

<div class="form-overlay" on:click|self={onClose}>
  <div class="form-container">
    <div class="form-header">
      <h2>{isEditing ? '编辑凭证' : '添加凭证'}</h2>
      <button class="close-btn" on:click={onClose}>×</button>
    </div>
    
    {#if error}
      <div class="error-message">{error}</div>
    {/if}
    
    <form on:submit|preventDefault={handleSubmit}>
      <div class="form-group">
        <label for="title">标题 *</label>
        <input
          type="text"
          id="title"
          bind:value={title}
          placeholder="例如：GitHub、淘宝"
          disabled={isLoading}
        />
      </div>
      
      <div class="form-group">
        <label for="username">用户名</label>
        <input
          type="text"
          id="username"
          bind:value={username}
          placeholder="邮箱或用户名"
          disabled={isLoading}
        />
      </div>
      
      <div class="form-group">
        <label for="password">密码 *</label>
        <div class="password-input">
          <input
            type={showPassword ? 'text' : 'password'}
            id="password"
            bind:value={password}
            placeholder="输入密码"
            disabled={isLoading}
          />
          <button
            type="button"
            class="toggle-password"
            on:click={() => showPassword = !showPassword}
          >
            {showPassword ? '隐藏' : '显示'}
          </button>
          <button
            type="button"
            class="generate-btn"
            on:click={handleGeneratePassword}
            disabled={isLoading}
          >
            生成
          </button>
        </div>
      </div>
      
      <div class="form-group">
        <label for="url">网址</label>
        <input
          type="url"
          id="url"
          bind:value={url}
          placeholder="https://example.com"
          disabled={isLoading}
        />
      </div>
      
      <div class="form-group">
        <label for="category">分类</label>
        <select id="category" bind:value={category} disabled={isLoading}>
          <option value="general">通用</option>
          <option value="social">社交媒体</option>
          <option value="development">开发</option>
          <option value="shopping">购物</option>
          <option value="finance">金融</option>
          <option value="email">邮箱</option>
          <option value="other">其他</option>
        </select>
      </div>
      
      <div class="form-group">
        <label for="notes">备注</label>
        <textarea
          id="notes"
          bind:value={notes}
          placeholder="可选备注信息"
          disabled={isLoading}
          rows="3"
        ></textarea>
      </div>
      
      <div class="form-group checkbox-group">
        <label>
          <input
            type="checkbox"
            bind:checked={isFavorite}
            disabled={isLoading}
          />
          收藏
        </label>
      </div>
      
      <div class="form-actions">
        <button type="button" class="cancel-btn" on:click={onClose} disabled={isLoading}>
          取消
        </button>
        <button type="submit" class="save-btn" disabled={isLoading}>
          {isLoading ? '保存中...' : (isEditing ? '更新' : '保存')}
        </button>
      </div>
    </form>
  </div>
</div>

<style>
  .form-overlay {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background: rgba(0, 0, 0, 0.5);
    display: flex;
    justify-content: center;
    align-items: center;
    z-index: 1000;
  }
  
  .form-container {
    background: white;
    border-radius: 1rem;
    width: 90%;
    max-width: 500px;
    max-height: 90vh;
    overflow-y: auto;
    padding: 2rem;
  }
  
  .form-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 1.5rem;
  }
  
  .form-header h2 {
    margin: 0;
    color: #333;
  }
  
  .close-btn {
    background: none;
    border: none;
    font-size: 1.5rem;
    cursor: pointer;
    color: #666;
    padding: 0.5rem;
  }
  
  .close-btn:hover {
    color: #333;
  }
  
  .error-message {
    color: #e74c3c;
    background: #fdeaea;
    padding: 0.75rem;
    border-radius: 0.5rem;
    margin-bottom: 1rem;
  }
  
  .form-group {
    margin-bottom: 1.25rem;
  }
  
  label {
    display: block;
    margin-bottom: 0.5rem;
    font-weight: 600;
    color: #555;
  }
  
  input, select, textarea {
    width: 100%;
    padding: 0.75rem;
    border: 2px solid #e0e0e0;
    border-radius: 0.5rem;
    font-size: 1rem;
    transition: border-color 0.3s;
    box-sizing: border-box;
  }
  
  input:focus, select:focus, textarea:focus {
    outline: none;
    border-color: #667eea;
  }
  
  .password-input {
    display: flex;
    gap: 0.5rem;
  }
  
  .password-input input {
    flex: 1;
  }
  
  .toggle-password, .generate-btn {
    padding: 0.75rem;
    border: 2px solid #e0e0e0;
    border-radius: 0.5rem;
    background: white;
    cursor: pointer;
    font-size: 0.9rem;
    color: #666;
  }
  
  .toggle-password:hover, .generate-btn:hover {
    background: #f0f0f0;
  }
  
  .checkbox-group label {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    font-weight: normal;
    cursor: pointer;
  }
  
  .checkbox-group input {
    width: auto;
  }
  
  .form-actions {
    display: flex;
    gap: 1rem;
    margin-top: 2rem;
  }
  
  .cancel-btn, .save-btn {
    flex: 1;
    padding: 0.75rem;
    border: none;
    border-radius: 0.5rem;
    font-size: 1rem;
    font-weight: 600;
    cursor: pointer;
    transition: transform 0.2s;
  }
  
  .cancel-btn {
    background: #f0f0f0;
    color: #666;
  }
  
  .cancel-btn:hover {
    background: #e0e0e0;
  }
  
  .save-btn {
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    color: white;
  }
  
  .save-btn:hover {
    transform: translateY(-2px);
  }
  
  .save-btn:disabled {
    opacity: 0.7;
    cursor: not-allowed;
    transform: none;
  }
</style>

// src/components/credentials/CredentialForm.tsx
import { useState, useEffect, useCallback, type FormEvent } from 'react';
import {
  X,
  Eye,
  EyeOff,
  RefreshCw,
  Plus,
  Loader2,
} from 'lucide-react';
import { Credential } from '@/lib/types';
import { cn } from '@/lib/utils';
import { useCredentialStore } from '@/stores/credentialStore';

interface CredentialFormProps {
  credential?: Credential | null;
  onClose: () => void;
}

interface FormData {
  title: string;
  username: string;
  password: string;
  url: string;
  category: string;
  notes: string;
  tags: string[];
}

interface FormErrors {
  title?: string;
  password?: string;
}

const PASSWORD_LENGTH = 16;
const PASSWORD_CHARS =
  'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()_+-=[]{}|;:,.<>?';

function generatePassword(): string {
  const array = new Uint32Array(PASSWORD_LENGTH);
  crypto.getRandomValues(array);
  return Array.from(array, (v) => PASSWORD_CHARS[v % PASSWORD_CHARS.length]).join('');
}

export default function CredentialForm({
  credential,
  onClose,
}: CredentialFormProps) {
  const {
    addCredential,
    updateCredential,
    decryptPassword,
    categories,
    tags: existingTags,
    isLoading,
  } = useCredentialStore();

  const isEditing = !!credential;

  const [form, setForm] = useState<FormData>({
    title: '',
    username: '',
    password: '',
    url: '',
    category: '',
    notes: '',
    tags: [],
  });

  const [errors, setErrors] = useState<FormErrors>({});
  const [showPassword, setShowPassword] = useState(false);
  const [tagInput, setTagInput] = useState('');
  const [submitError, setSubmitError] = useState<string | null>(null);

  // 编辑模式：加载已有凭证数据
  useEffect(() => {
    if (credential) {
      const loadForm = async () => {
        let decryptedPwd = '';
        try {
          decryptedPwd = await decryptPassword(credential.password);
        } catch {
          decryptedPwd = '';
        }
        setForm({
          title: credential.title,
          username: credential.username || '',
          password: decryptedPwd,
          url: credential.url || '',
          category: credential.category || '',
          notes: credential.notes || '',
          tags: [...credential.tags],
        });
      };
      loadForm();
    }
  }, [credential, decryptPassword]);

  const handleChange = useCallback(
    (field: keyof FormData, value: string | string[]) => {
      setForm((prev) => ({ ...prev, [field]: value }));
      // 清除对应字段的错误
      if (errors[field as keyof FormErrors]) {
        setErrors((prev) => ({ ...prev, [field]: undefined }));
      }
    },
    [errors]
  );

  const handleGeneratePassword = useCallback(() => {
    const pwd = generatePassword();
    setForm((prev) => ({ ...prev, password: pwd }));
    setShowPassword(true);
    if (errors.password) {
      setErrors((prev) => ({ ...prev, password: undefined }));
    }
  }, [errors.password]);

  const handleAddTag = useCallback(() => {
    const tag = tagInput.trim();
    if (tag && !form.tags.includes(tag)) {
      setForm((prev) => ({ ...prev, tags: [...prev.tags, tag] }));
    }
    setTagInput('');
  }, [tagInput, form.tags]);

  const handleRemoveTag = useCallback((tagToRemove: string) => {
    setForm((prev) => ({
      ...prev,
      tags: prev.tags.filter((t) => t !== tagToRemove),
    }));
  }, []);

  const handleTagInputKeyDown = useCallback(
    (e: React.KeyboardEvent<HTMLInputElement>) => {
      if (e.key === 'Enter') {
        e.preventDefault();
        handleAddTag();
      }
    },
    [handleAddTag]
  );

  const validate = useCallback((): boolean => {
    const newErrors: FormErrors = {};

    if (!form.title.trim()) {
      newErrors.title = '请输入凭证标题';
    }

    if (!form.password.trim()) {
      newErrors.password = '请输入密码';
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  }, [form.title, form.password]);

  const handleSubmit = useCallback(
    async (e: FormEvent) => {
      e.preventDefault();
      setSubmitError(null);

      if (!validate()) return;

      try {
        const data = {
          title: form.title.trim(),
          username: form.username.trim() || undefined,
          password: form.password,
          url: form.url.trim() || undefined,
          category: form.category || undefined,
          notes: form.notes.trim() || undefined,
          tags: form.tags,
        };

        if (isEditing && credential?.id) {
          await updateCredential(credential.id, data);
        } else {
          await addCredential(data);
        }

        onClose();
      } catch {
        setSubmitError(isEditing ? '更新凭证失败' : '添加凭证失败');
      }
    },
    [form, validate, isEditing, credential, addCredential, updateCredential, onClose]
  );

  // 获取建议标签（已有的但当前未选择的）
  const suggestedTags = existingTags.filter(
    (tag) =>
      !form.tags.includes(tag) &&
      tag.toLowerCase().includes(tagInput.toLowerCase())
  );

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4">
      <div
        className={cn(
          'relative flex max-h-[90vh] w-full max-w-lg flex-col rounded-2xl bg-white shadow-xl',
          'dark:bg-gray-800'
        )}
      >
        {/* 头部 */}
        <div className="flex items-center justify-between border-b border-gray-200 px-6 py-4 dark:border-gray-700">
          <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">
            {isEditing ? '编辑凭证' : '添加凭证'}
          </h2>
          <button
            onClick={onClose}
            className="rounded-md p-1.5 text-gray-400 hover:bg-gray-100 hover:text-gray-600 dark:hover:bg-gray-700 dark:hover:text-gray-300"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* 表单内容 */}
        <form
          onSubmit={handleSubmit}
          className="flex flex-1 flex-col overflow-y-auto px-6 py-4"
        >
          <div className="flex flex-col gap-4">
            {/* 标题 */}
            <div>
              <label className="mb-1 block text-sm font-medium text-gray-700 dark:text-gray-300">
                标题 <span className="text-red-500">*</span>
              </label>
              <input
                type="text"
                value={form.title}
                onChange={(e) => handleChange('title', e.target.value)}
                placeholder="例如：GitHub"
                className={cn(
                  'w-full rounded-lg border bg-white px-3 py-2 text-sm text-gray-900 placeholder-gray-400',
                  'focus:outline-none focus:ring-2 focus:ring-blue-500',
                  'dark:border-gray-600 dark:bg-gray-900 dark:text-gray-100 dark:placeholder-gray-500',
                  errors.title
                    ? 'border-red-500 focus:ring-red-500'
                    : 'border-gray-300 dark:border-gray-600'
                )}
              />
              {errors.title && (
                <p className="mt-1 text-xs text-red-500">{errors.title}</p>
              )}
            </div>

            {/* 用户名 */}
            <div>
              <label className="mb-1 block text-sm font-medium text-gray-700 dark:text-gray-300">
                用户名
              </label>
              <input
                type="text"
                value={form.username}
                onChange={(e) => handleChange('username', e.target.value)}
                placeholder="例如：user@example.com"
                className="w-full rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-900 dark:text-gray-100 dark:placeholder-gray-500"
              />
            </div>

            {/* 密码 */}
            <div>
              <label className="mb-1 block text-sm font-medium text-gray-700 dark:text-gray-300">
                密码 <span className="text-red-500">*</span>
              </label>
              <div className="flex items-center gap-2">
                <div className="relative flex-1">
                  <input
                    type={showPassword ? 'text' : 'password'}
                    value={form.password}
                    onChange={(e) => handleChange('password', e.target.value)}
                    placeholder="输入密码"
                    className={cn(
                      'w-full rounded-lg border bg-white px-3 py-2 pr-10 text-sm text-gray-900 placeholder-gray-400',
                      'focus:outline-none focus:ring-2 focus:ring-blue-500',
                      'dark:border-gray-600 dark:bg-gray-900 dark:text-gray-100 dark:placeholder-gray-500',
                      errors.password
                        ? 'border-red-500 focus:ring-red-500'
                        : 'border-gray-300 dark:border-gray-600'
                    )}
                  />
                  <button
                    type="button"
                    onClick={() => setShowPassword((v) => !v)}
                    className="absolute right-2 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600 dark:hover:text-gray-300"
                  >
                    {showPassword ? (
                      <EyeOff className="h-4 w-4" />
                    ) : (
                      <Eye className="h-4 w-4" />
                    )}
                  </button>
                </div>
                <button
                  type="button"
                  onClick={handleGeneratePassword}
                  className="shrink-0 rounded-lg border border-gray-300 p-2 text-gray-500 hover:bg-gray-100 hover:text-gray-700 dark:border-gray-600 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-gray-200"
                  title="生成随机密码"
                >
                  <RefreshCw className="h-4 w-4" />
                </button>
              </div>
              {errors.password && (
                <p className="mt-1 text-xs text-red-500">{errors.password}</p>
              )}
            </div>

            {/* URL */}
            <div>
              <label className="mb-1 block text-sm font-medium text-gray-700 dark:text-gray-300">
                URL
              </label>
              <input
                type="url"
                value={form.url}
                onChange={(e) => handleChange('url', e.target.value)}
                placeholder="https://example.com"
                className="w-full rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-900 dark:text-gray-100 dark:placeholder-gray-500"
              />
            </div>

            {/* 分类 */}
            <div>
              <label className="mb-1 block text-sm font-medium text-gray-700 dark:text-gray-300">
                分类
              </label>
              <select
                value={form.category}
                onChange={(e) => handleChange('category', e.target.value)}
                className="w-full rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm text-gray-900 focus:outline-none focus:ring-2 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-900 dark:text-gray-100"
              >
                <option value="">选择分类</option>
                {categories.map((cat) => (
                  <option key={cat} value={cat}>
                    {cat}
                  </option>
                ))}
              </select>
            </div>

            {/* 备注 */}
            <div>
              <label className="mb-1 block text-sm font-medium text-gray-700 dark:text-gray-300">
                备注
              </label>
              <textarea
                value={form.notes}
                onChange={(e) => handleChange('notes', e.target.value)}
                placeholder="添加备注信息..."
                rows={3}
                className="w-full resize-none rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-900 dark:text-gray-100 dark:placeholder-gray-500"
              />
            </div>

            {/* 标签 */}
            <div>
              <label className="mb-1 block text-sm font-medium text-gray-700 dark:text-gray-300">
                标签
              </label>
              <div className="flex flex-wrap gap-1.5">
                {form.tags.map((tag) => (
                  <span
                    key={tag}
                    className="inline-flex items-center gap-1 rounded-full bg-gray-100 px-2.5 py-0.5 text-xs font-medium text-gray-700 dark:bg-gray-700 dark:text-gray-300"
                  >
                    {tag}
                    <button
                      type="button"
                      onClick={() => handleRemoveTag(tag)}
                      className="text-gray-400 hover:text-gray-600 dark:hover:text-gray-200"
                    >
                      <X className="h-3 w-3" />
                    </button>
                  </span>
                ))}
              </div>
              <div className="mt-1.5 flex items-center gap-2">
                <input
                  type="text"
                  value={tagInput}
                  onChange={(e) => setTagInput(e.target.value)}
                  onKeyDown={handleTagInputKeyDown}
                  placeholder="输入标签后按回车"
                  className="flex-1 rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-900 dark:text-gray-100 dark:placeholder-gray-500"
                />
                <button
                  type="button"
                  onClick={handleAddTag}
                  disabled={!tagInput.trim()}
                  className="shrink-0 rounded-lg border border-gray-300 p-2 text-gray-500 hover:bg-gray-100 hover:text-gray-700 disabled:cursor-not-allowed disabled:opacity-50 dark:border-gray-600 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-gray-200"
                >
                  <Plus className="h-4 w-4" />
                </button>
              </div>
              {/* 标签建议 */}
              {tagInput && suggestedTags.length > 0 && (
                <div className="mt-1 flex flex-wrap gap-1">
                  {suggestedTags.slice(0, 5).map((tag) => (
                    <button
                      key={tag}
                      type="button"
                      onClick={() => {
                        setForm((prev) => ({
                          ...prev,
                          tags: [...prev.tags, tag],
                        }));
                        setTagInput('');
                      }}
                      className="rounded-full bg-blue-50 px-2 py-0.5 text-xs text-blue-600 hover:bg-blue-100 dark:bg-blue-900/20 dark:text-blue-400 dark:hover:bg-blue-900/30"
                    >
                      + {tag}
                    </button>
                  ))}
                </div>
              )}
            </div>
          </div>

          {/* 提交错误 */}
          {submitError && (
            <div className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-600 dark:bg-red-900/20 dark:text-red-400">
              {submitError}
            </div>
          )}
        </form>

        {/* 底部按钮 */}
        <div className="flex items-center justify-end gap-3 border-t border-gray-200 px-6 py-4 dark:border-gray-700">
          <button
            type="button"
            onClick={onClose}
            className="rounded-lg border border-gray-300 px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 dark:border-gray-600 dark:text-gray-300 dark:hover:bg-gray-700"
          >
            取消
          </button>
          <button
            type="submit"
            onClick={handleSubmit}
            disabled={isLoading}
            className={cn(
              'inline-flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-medium text-white',
              'bg-blue-600 hover:bg-blue-700',
              'disabled:cursor-not-allowed disabled:opacity-50',
              'dark:bg-blue-500 dark:hover:bg-blue-600'
            )}
          >
            {isLoading && <Loader2 className="h-4 w-4 animate-spin" />}
            {isEditing ? '保存' : '添加'}
          </button>
        </div>
      </div>
    </div>
  );
}
